name: "Build iOS IPA app"

on:
  # manual trigger but change to any supported event
  workflow_dispatch:
    branches: [main]

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - uses: sparkfabrik/ios-build-action@v1.2.0
        with:
            upload-to-testflight: false
            increment-build-number: false
            build-pods: true
            pods-path: "brain/client/ios/App/Podfile"
            configuration: Release
            export-method: development
            workspace-path: "brain/client/ios/App/App.xcworkspace"
            project-path: "brain/client/ios/App/App.xcodeproj"
            scheme: StarTrack
            output-path: build-${{ github.sha }}.ipa
            p12-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
            mobileprovision-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
            code-signing-identity: ${{ secrets.TEAM_NAME }}
            # apple-key-id: ${{ secrets.APPLE_KEY_ID }}
            # apple-key-issuer-id: ${{ secrets.APPLE_KEY_ISSUER_ID }}
            # apple-key-content: ${{ secrets.APPLE_KEY_CONTENT }}
            team-id: ${{ secrets.TEAM_ID }}
            # team-name: ${{ secrets.TEAM_NAME }}
            # match-password: ${{ secrets.MATCH_PASSWORD }}
            # match-git-url: ${{ secrets.MATCH_GIT_URL }}
            # match-git-basic-authorization: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
            # match-build-type: "development"
            # browserstack-upload: true
            # browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
            # browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            # fastlane-env: stage
            ios-app-id: eu.vpelloin.startrack
